CompileFlags:
  Add: [ -Wall, -Wextra, -ferror-limit=0, -Wno-unknown-pragmas ]
---
  If:
      PathMatch: [.*\.c$, .*\.h$]
  CompileFlags:
    Add: [ -std=c23 ]

---
  If:
      PathMatch: [.*\.cpp$, .*\.hpp$]
  CompileFlags:
    Add: [ -std=c++14, -Wnrvo, -Wno-c++17-extensions, -Wno-deprecated ]
